on:
  push:
    branches:
      - main
jobs:
  strip-modules:
    name: Strip Modules and Commit Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cleanup
        run: |
          # find src -type f -exec sed -i '/\/\/\$StripStart/,/\/\/\$StripEnd/d' {} \;
      - name: Remove release branch
        run: |
          git push origin --delete release
      - name: Commit Changes
        run: |
          git config --local user.email "githubactions@our-space.xyz"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Stripped Modules"
          git push origin main:release